<a href="https://colab.research.google.com/github/pythonuzgit/elmurodov/blob/master/Natural%20Language%20Processing%20using%20Gensim/Training_Word_Embedding%2C_Gensim_and_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import re
import string

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import TweetTokenizer

In [ ]:
training_data = pd.read_csv('/content/fake_news_train_clean.csv')
training_data.head()

Unnamed: 0                                          title_txt  label
0           0  hous dem aid didnt even see comey letter jason...      1
1           1  flynn hillari clinton big woman campu  breitba...      0
2           2  truth might get fire truth might get fire octo...      1
3           3  15 civilian kill singl us airstrik identifi vi...      1
4           4  iranian woman jail fiction unpublish stori wom...      1

In [ ]:
import gensim

In [ ]:
(
    training_data
    .title_txt
    .apply(lambda x: x.split(" "))
    .head()
    .values
 )

array([list(['hous', 'dem', 'aid', 'didnt', 'even', 'see', 'comey', 'letter', 'jason', 'chaffetz', 'tweet', 'hous', 'dem', 'aid', 'didnt', 'even', 'see', 'comey', 'letter', 'jason', 'chaffetz', 'tweet', 'darrel', 'lucu', 'octob', '30', '2016', 'subscrib', 'jason', 'chaffetz', 'stump', 'american', 'fork', 'utah', '', 'imag', 'courtesi', 'michael', 'jolley', 'avail', 'creativ', 'commonsbi', 'licens', 'apolog', 'keith', 'olbermann', 'doubt', 'worst', 'person', 'world', 'week–fbi', 'director', 'jame', 'comey', 'accord', 'hous', 'democrat', 'aid', 'look', 'like', 'also', 'know', 'secondworst', 'person', 'well', 'turn', 'comey', 'sent', 'nowinfam', 'letter', 'announc', 'fbi', 'look', 'email', 'may', 'relat', 'hillari', 'clinton', 'email', 'server', 'rank', 'democrat', 'relev', 'committe', 'didnt', 'hear', 'comey', 'found', 'via', 'tweet', 'one', 'republican', 'committe', 'chairmen', 'know', 'comey', 'notifi', 'republican', 'chairmen', 'democrat', 'rank', 'member', 'hous', 'intellig', 'judici

In [ ]:
training_corpus = training_data.title_txt.apply(lambda x: x.split(" "))

model = gensim.models.Word2Vec(sentences = training_corpus)

Use wordvectors from the model object "model.wv

In [ ]:
model.wv.vocab

{'hous': <gensim.models.keyedvectors.Vocab at 0x7f7b29818e90>,
 'dem': <gensim.models.keyedvectors.Vocab at 0x7f7b24075650>,
 'aid': <gensim.models.keyedvectors.Vocab at 0x7f7b24075690>,
 'didnt': <gensim.models.keyedvectors.Vocab at 0x7f7b240759d0>,
 'even': <gensim.models.keyedvectors.Vocab at 0x7f7b24075750>,
 'see': <gensim.models.keyedvectors.Vocab at 0x7f7b24075bd0>,
 'comey': <gensim.models.keyedvectors.Vocab at 0x7f7b24075b90>,
 'letter': <gensim.models.keyedvectors.Vocab at 0x7f7b24075dd0>,
 'jason': <gensim.models.keyedvectors.Vocab at 0x7f7b24075b10>,
 'chaffetz': <gensim.models.keyedvectors.Vocab at 0x7f7b24075c90>,
 'tweet': <gensim.models.keyedvectors.Vocab at 0x7f7b24075e90>,
 'darrel': <gensim.models.keyedvectors.Vocab at 0x7f7b24075d50>,
 'lucu': <gensim.models.keyedvectors.Vocab at 0x7f7b24075ed0>,
 'octob': <gensim.models.keyedvectors.Vocab at 0x7f7b24075e50>,
 '30': <gensim.models.keyedvectors.Vocab at 0x7f7b24075f10>,
 '2016': <gensim.models.keyedvectors.Vocab at 0

In [ ]:
model.wv.most_similar("democrat")

[('republican', 0.855959415435791),
 ('gop', 0.7109729647636414),
 ('incumb', 0.6944029927253723),
 ('superdeleg', 0.6415075063705444),
 ('bipartisan', 0.6388217210769653),
 ('constitu', 0.6322923302650452),
 ('conserv', 0.6103998422622681),
 ('senat', 0.6072127819061279),
 ('congressmen', 0.5920042991638184),
 ('filibust', 0.587761402130127)]

In [ ]:
model.wv.vectors

array([[ 0.6103215 , -2.5148368 ,  0.60511196, ..., -0.09141511,
        -1.5074288 ,  2.532957  ],
       [-0.38420817,  0.4463487 , -1.1149518 , ...,  1.5803078 ,
        -0.28642476, -0.9606708 ],
       [-1.6360127 , -0.9121378 , -0.73103625, ..., -1.1250101 ,
         2.0896308 ,  0.03086756],
       ...,
       [-0.02727876,  0.00461281, -0.03647577, ..., -0.10297391,
        -0.03992091,  0.07253943],
       [ 0.04656462, -0.02098807, -0.01985152, ..., -0.07737929,
        -0.06716258,  0.07350485],
       [ 0.05158159,  0.0436484 , -0.07358016, ..., -0.08161225,
        -0.10841641, -0.00650284]], dtype=float32)

Pytorch

In [ ]:
class MyBackpack():
  pass

In [ ]:
class MyBackPack():
  def __init__(self):
    self.container = []

  def hold(self, obj):
    self.container.append(obj)  

In [ ]:
backpack = MyBackPack()
backpack.hold("candy")


In [ ]:
print(backpack.container)

['candy']


In [ ]:
class Container():
  def __init__(self):
    self.message = 'I am a container whoo'

In [ ]:
class MyBackPack(Container):
  def __init__(self):
    super().__init__()
    self.container = []

  def hold(self, obj):
    self.container.append(obj)  

In [ ]:
backpack = MyBackPack()
backpack.hold("candy")

In [ ]:
print(backpack.message)

I am a container whoo


Import the torch package

In [ ]:
import torch
import torch.nn as nn

Create neural network. This network is a simple two layer neural network that takes features in the first layer and outputs predictions within the second layer

In [ ]:
class FirstNeuralNetwork(nn.Module):
  def __init__(self, input_size, hidden_size, num_classes):
    super().__init__()
    self.layer1 = nn.Linear(input_size, hidden_size)
    self.relu = nn.ReLU()
    self.layer2 = nn.Linear(hidden_size, num_classes)

  def forward(self, x):
    pass  

Every model created using pytorch must define a function called forward, which takes in the data you want to pass into your network and spits out the outut of the network

In [ ]:
class FirstNeuralNetwork(nn.Module):
  def __init__(self, input_size, hidden_size, num_classes):
    super().__init__()
    self.layer1 = nn.Linear(input_size, hidden_size)
    self.relu = nn.ReLU()
    self.layer2 = nn.Linear(hidden_size, num_classes)

  def forward(self, data_input):
    output_layer1 = self.layer1(data_input)
    output_layer1 = self.relu(output_layer1)
    output_layer2 = self.layer2(output_layer1)

    return output_layer2


the model

In [ ]:
first_neural_network = FirstNeuralNetwork(300, 100, 2)
print(first_neural_network)

FirstNeuralNetwork(
  (layer1): Linear(in_features=300, out_features=100, bias=True)
  (relu): ReLU()
  (layer2): Linear(in_features=100, out_features=2, bias=True)
)


Train a model

In [ ]:
sentence_length = training_data.title_txt.apply(lambda x: x.split(" ")).apply(len).max()
sentence_length

20480

Get a dictionary mapping of the vocab

In [ ]:
word_map = {
    word:idx
    for idx,word in enumerate(model.wv.vocab, start=2)
}
word_map

{'hous': 2,
 'dem': 3,
 'aid': 4,
 'didnt': 5,
 'even': 6,
 'see': 7,
 'comey': 8,
 'letter': 9,
 'jason': 10,
 'chaffetz': 11,
 'tweet': 12,
 'darrel': 13,
 'lucu': 14,
 'octob': 15,
 '30': 16,
 '2016': 17,
 'subscrib': 18,
 'stump': 19,
 'american': 20,
 'fork': 21,
 'utah': 22,
 '': 23,
 'imag': 24,
 'courtesi': 25,
 'michael': 26,
 'avail': 27,
 'creativ': 28,
 'licens': 29,
 'apolog': 30,
 'keith': 31,
 'olbermann': 32,
 'doubt': 33,
 'worst': 34,
 'person': 35,
 'world': 36,
 'director': 37,
 'jame': 38,
 'accord': 39,
 'democrat': 40,
 'look': 41,
 'like': 42,
 'also': 43,
 'know': 44,
 'well': 45,
 'turn': 46,
 'sent': 47,
 'nowinfam': 48,
 'announc': 49,
 'fbi': 50,
 'email': 51,
 'may': 52,
 'relat': 53,
 'hillari': 54,
 'clinton': 55,
 'server': 56,
 'rank': 57,
 'relev': 58,
 'committe': 59,
 'hear': 60,
 'found': 61,
 'via': 62,
 'one': 63,
 'republican': 64,
 'chairmen': 65,
 'notifi': 66,
 'member': 67,
 'intellig': 68,
 'judiciari': 69,
 'oversight': 70,
 'agenc': 71,
 

So now we have words assiciated with numbers. This is important the neural network model can know which embedding index to use

In [ ]:
(
    training_data
    .title_txt
    .apply(lambda x: x.split(" "))
)[0]

['hous',
 'dem',
 'aid',
 'didnt',
 'even',
 'see',
 'comey',
 'letter',
 'jason',
 'chaffetz',
 'tweet',
 'hous',
 'dem',
 'aid',
 'didnt',
 'even',
 'see',
 'comey',
 'letter',
 'jason',
 'chaffetz',
 'tweet',
 'darrel',
 'lucu',
 'octob',
 '30',
 '2016',
 'subscrib',
 'jason',
 'chaffetz',
 'stump',
 'american',
 'fork',
 'utah',
 '',
 'imag',
 'courtesi',
 'michael',
 'jolley',
 'avail',
 'creativ',
 'commonsbi',
 'licens',
 'apolog',
 'keith',
 'olbermann',
 'doubt',
 'worst',
 'person',
 'world',
 'week–fbi',
 'director',
 'jame',
 'comey',
 'accord',
 'hous',
 'democrat',
 'aid',
 'look',
 'like',
 'also',
 'know',
 'secondworst',
 'person',
 'well',
 'turn',
 'comey',
 'sent',
 'nowinfam',
 'letter',
 'announc',
 'fbi',
 'look',
 'email',
 'may',
 'relat',
 'hillari',
 'clinton',
 'email',
 'server',
 'rank',
 'democrat',
 'relev',
 'committe',
 'didnt',
 'hear',
 'comey',
 'found',
 'via',
 'tweet',
 'one',
 'republican',
 'committe',
 'chairmen',
 'know',
 'comey',
 'notifi',

In [ ]:
training_sentence_data = (
    training_data
    .title_txt
    .apply(lambda x: list(map(lambda word: word_map[word] if word in word_map else 1, x.split(" "))))
)

print(training_sentence_data[0])

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 10, 11, 19, 20, 21, 22, 23, 24, 25, 26, 1, 27, 28, 1, 29, 30, 31, 32, 33, 34, 35, 36, 1, 37, 38, 8, 39, 2, 40, 4, 41, 42, 43, 44, 1, 35, 45, 46, 8, 47, 48, 9, 49, 50, 41, 51, 52, 53, 54, 55, 51, 56, 57, 40, 58, 59, 5, 60, 8, 61, 62, 12, 63, 64, 59, 65, 44, 8, 66, 64, 65, 40, 57, 67, 2, 68, 69, 70, 59, 71, 72, 51, 73, 74, 75, 7, 76, 77, 78, 79, 9, 80, 70, 59, 81, 10, 11, 82, 83, 36, 84, 12, 50, 85, 78, 50, 86, 87, 51, 88, 89, 90, 91, 92, 93, 10, 11, 94, 15, 95, 17, 96, 44, 91, 23, 8, 97, 98, 72, 51, 99, 100, 1, 44, 101, 102, 103, 104, 105, 106, 107, 108, 5, 109, 11, 22, 64, 110, 111, 112, 113, 90, 54, 1, 114, 115, 116, 117, 118, 119, 120, 117, 105, 11, 121, 50, 110, 122, 1, 12, 123, 124, 125, 126, 127, 128, 129, 39, 130, 2, 40, 4, 131, 9, 52, 114, 11, 132, 4, 133, 134, 135, 40, 5, 6, 44, 8, 9, 1, 61, 136, 137, 40, 57, 67, 58, 59, 5, 138, 8, 9, 64, 65, 108, 40, 57, 67, 138, 81, 70, 139, 140, 

0 pad each sentence so every sentence is the same length for the network to learn

In [ ]:
training_sentence_data = (
    list(
        map(
            lambda x: pd.np.pad(x, (0, sentence_length - len(x))),
            training_sentence_data
        )
    )
)

training_sentence_data[0]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  after removing the cwd from sys.path.


array([2, 3, 4, ..., 0, 0, 0])

Convert these numbers to tensors

In [ ]:
torch.LongTensor(training_sentence_data[0])

tensor([2, 3, 4,  ..., 0, 0, 0])

In [ ]:
training_sentence_data = (
    list(
        map(
            lambda x: torch.LongTensor(x),
            training_sentence_data
        )
    )
)

training_sentence_data[0]

tensor([2, 3, 4,  ..., 0, 0, 0])

Find vocabularly

In [ ]:
pd.np.random.seed(100)
model.wv.vectors.shape

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  """Entry point for launching an IPython kernel.


(39950, 100)

In [ ]:
word_vectors_for_training = pd.np.insert(
    model.wv.vectors,
    0,
    pd.np.random.uniform(model.wv.vectors.min(),model.wv.vectors.max(),100),
    axis=0)

word_vectors_for_training = pd.np.insert(
    word_vectors_for_training,
    0,
    pd.np.zeros(100),
    axis = 0
)

word_vectors_for_training = torch.FloatTensor(
    word_vectors_for_training
)
word_vectors_for_training.shape

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  # Remove the CWD from sys.path while we load stuff.


torch.Size([39952, 100])

Embedding layer and process the data

In [ ]:
class FirstNeuralNetwork(nn.Module):
  def __init__(self, input_size, hidden_size, num_classes):
    super().__init__()
    self.embedding_layer = nn.EmbeddingBag.from_pretrained(word_vectors_for_training,
                                                           mode = 'mean')
    self.layer1 = nn.Linear(input_size, hidden_size)
    self.relu = nn.ReLU()
    self.layer2 = nn.Linear(hidden_size, num_classes)



  def forward(self, data_input):
    embedded_data_input = self.embedding_layer(data_input)
    output_layer1 = self.layer1(embedded_data_input) 
    output_layer1 = self.relu(output_layer1)
    output_layer2 = self.layer2(output_layer1)

    return output_layer2.squeeze() 

finalize the training data

In [ ]:
training_sentence_data = torch.stack(training_sentence_data)

Define the network

In [ ]:
first_neural_network = FirstNeuralNetwork(100, 50, 1)

Import torch.utils.data

In [ ]:
import torch.utils.data as data

DataLoader and dataet

In [ ]:
dataset = data.TensorDataset(training_sentence_data, torch.FloatTensor(training_data.label.values))
dataloader = data.DataLoader(dataset, batch_size=256)

Use BinaryCrossEntropy loss function

In [ ]:
import torch.optim as optim

In [ ]:
optimizer = optim.Adam(first_neural_network.parameters(), lr = 0.001)
loss_fn = nn.BCEWithLogitsLoss()


In [ ]:
loss = nn.BCEWithLogitsLoss()
in_mat = torch.randn(3, requires_grad=True)
tar_mat = torch.empty(3).random_(2)
output = loss(in_mat, tar_mat)

In [ ]:
print(in_mat)
print(tar_mat)
print(output)

tensor([-1.1135, -1.2671,  0.6669], requires_grad=True)
tensor([1., 1., 0.])
tensor(1.3313, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [ ]:
import tqdm

for n in tqdm.tqdm(range(100)):
  avg_loss = []
  for batch in dataloader:
    #batch[0] - the sentence data or X
    #batch[1] - the label for each sentence or Y
    optimizer.zero_grad()
    #pass the model into the batch
    output = first_neural_network(batch[0])
    #output = first_neural_network(batch[0])
    #calculate the loss function
    loss = loss_fn(output, batch[1])
    avg_loss.append(loss.item())
    loss.backward()
    optimizer.step()


  print(pd.np.mean(avg_loss))  



  1%|          | 1/100 [00:05<09:34,  5.81s/it]

0.6812112306555113


  2%|▏         | 2/100 [00:10<08:51,  5.42s/it]

0.6562748013271226


  3%|▎         | 3/100 [00:16<08:33,  5.29s/it]

0.6120421455966102


  4%|▍         | 4/100 [00:21<08:22,  5.23s/it]

0.5629869509074423


  5%|▌         | 5/100 [00:26<08:14,  5.20s/it]

0.5198361033366786


  6%|▌         | 6/100 [00:31<08:07,  5.18s/it]

0.4840787773331006


  7%|▋         | 7/100 [00:36<08:00,  5.16s/it]

0.4542248811986711


  8%|▊         | 8/100 [00:42<08:06,  5.29s/it]

0.42860319424006676


  9%|▉         | 9/100 [00:47<07:57,  5.24s/it]

0.4061233877307839


 10%|█         | 10/100 [00:52<07:49,  5.22s/it]

0.3864283830755287


 11%|█         | 11/100 [00:57<07:43,  5.21s/it]

0.3693230450153351


 12%|█▏        | 12/100 [01:02<07:37,  5.20s/it]

0.3545754539469878


 13%|█▎        | 13/100 [01:08<07:32,  5.20s/it]

0.34190579627950984


 14%|█▍        | 14/100 [01:13<07:26,  5.19s/it]

0.3309725167022811


 15%|█▌        | 15/100 [01:18<07:20,  5.18s/it]

0.321466123064359


 16%|█▌        | 16/100 [01:23<07:14,  5.17s/it]

0.3130939085450437


 17%|█▋        | 17/100 [01:28<07:09,  5.17s/it]

0.3056024012880193


 18%|█▊        | 18/100 [01:33<07:04,  5.17s/it]

0.2987906825211313


 19%|█▉        | 19/100 [01:39<06:59,  5.18s/it]

0.2925630617472861


 20%|██        | 20/100 [01:44<06:53,  5.16s/it]

0.28683930366403526


 21%|██        | 21/100 [01:49<06:47,  5.16s/it]

0.28155202894575065


 22%|██▏       | 22/100 [01:54<06:42,  5.16s/it]

0.27663592414723503


 23%|██▎       | 23/100 [01:59<06:37,  5.16s/it]

0.27204821983145344


 24%|██▍       | 24/100 [02:04<06:31,  5.16s/it]

0.26774071839948493


 25%|██▌       | 25/100 [02:10<06:35,  5.27s/it]

0.26369158840841717


 26%|██▌       | 26/100 [02:15<06:26,  5.22s/it]

0.2598768108420902


 27%|██▋       | 27/100 [02:20<06:19,  5.20s/it]

0.25626285353468525


 28%|██▊       | 28/100 [02:25<06:12,  5.18s/it]

0.25281768540541333


 29%|██▉       | 29/100 [02:30<06:07,  5.17s/it]

0.24952883190578884


 30%|███       | 30/100 [02:36<06:01,  5.16s/it]

0.246366866139902


 31%|███       | 31/100 [02:41<05:56,  5.16s/it]

0.24332109155754247


 32%|███▏      | 32/100 [02:46<05:50,  5.16s/it]

0.24037975528173977


 33%|███▎      | 33/100 [02:51<05:45,  5.16s/it]

0.23752834068404305


 34%|███▍      | 34/100 [02:56<05:41,  5.17s/it]

0.23475733978880775


 35%|███▌      | 35/100 [03:01<05:36,  5.17s/it]

0.23205807184179625


 36%|███▌      | 36/100 [03:07<05:30,  5.16s/it]

0.2294187754806545


 37%|███▋      | 37/100 [03:12<05:25,  5.16s/it]

0.22683074490891564


 38%|███▊      | 38/100 [03:17<05:19,  5.16s/it]

0.2243169473691119


 39%|███▉      | 39/100 [03:22<05:14,  5.16s/it]

0.22185429827206665


 40%|████      | 40/100 [03:27<05:09,  5.15s/it]

0.21945252207418284


 41%|████      | 41/100 [03:32<05:03,  5.15s/it]

0.21709321894579464


 42%|████▏     | 42/100 [03:37<04:57,  5.14s/it]

0.2147799370189508


 43%|████▎     | 43/100 [03:43<04:59,  5.25s/it]

0.21251033370693526


 44%|████▍     | 44/100 [03:48<04:51,  5.21s/it]

0.21027997467252943


 45%|████▌     | 45/100 [03:53<04:45,  5.19s/it]

0.20808753867944083


 46%|████▌     | 46/100 [03:58<04:38,  5.17s/it]

0.20592791525026163


 47%|████▋     | 47/100 [04:03<04:33,  5.16s/it]

0.20380019706984362


 48%|████▊     | 48/100 [04:09<04:27,  5.15s/it]

0.20170771537555587


 49%|████▉     | 49/100 [04:14<04:22,  5.15s/it]

0.1996526275244024


 50%|█████     | 50/100 [04:19<04:17,  5.15s/it]

0.19762363967796168


 51%|█████     | 51/100 [04:24<04:12,  5.15s/it]

0.1956257830477423


 52%|█████▏    | 52/100 [04:29<04:06,  5.14s/it]

0.19365077796909544


 53%|█████▎    | 53/100 [04:34<04:01,  5.13s/it]

0.19168982199496692


 54%|█████▍    | 54/100 [04:39<03:55,  5.13s/it]

0.18974641317294705


 55%|█████▌    | 55/100 [04:44<03:50,  5.13s/it]

0.18782229514585602


 56%|█████▌    | 56/100 [04:50<03:45,  5.13s/it]

0.18591422711809477


 57%|█████▋    | 57/100 [04:55<03:40,  5.12s/it]

0.18403166863653395


 58%|█████▊    | 58/100 [05:00<03:35,  5.13s/it]

0.18217190148101914


 59%|█████▉    | 59/100 [05:05<03:30,  5.14s/it]

0.18032910260889265


 60%|██████    | 60/100 [05:11<03:30,  5.25s/it]

0.17851069010794163


 61%|██████    | 61/100 [05:16<03:23,  5.21s/it]

0.17672781377202934


 62%|██████▏   | 62/100 [05:21<03:17,  5.19s/it]

0.17498295878370604


 63%|██████▎   | 63/100 [05:26<03:11,  5.18s/it]

0.1732665327274137


 64%|██████▍   | 64/100 [05:31<03:05,  5.16s/it]

0.1715916076468097


 65%|██████▌   | 65/100 [05:36<03:00,  5.15s/it]

0.16994795989659098


 66%|██████▌   | 66/100 [05:41<02:54,  5.14s/it]

0.16835146894057593


 67%|██████▋   | 67/100 [05:46<02:49,  5.13s/it]

0.16678838369747004


 68%|██████▊   | 68/100 [05:52<02:44,  5.14s/it]

0.16527746431529522


 69%|██████▉   | 69/100 [05:57<02:39,  5.14s/it]

0.1638195134906305


 70%|███████   | 70/100 [06:02<02:34,  5.14s/it]

0.16240477489514482


 71%|███████   | 71/100 [06:07<02:29,  5.15s/it]

0.16105526230401462


 72%|███████▏  | 72/100 [06:12<02:24,  5.14s/it]

0.1597620731012689


 73%|███████▎  | 73/100 [06:17<02:18,  5.14s/it]

0.1585113528288073


 74%|███████▍  | 74/100 [06:22<02:13,  5.14s/it]

0.15730764654775461


 75%|███████▌  | 75/100 [06:28<02:08,  5.14s/it]

0.15616082772612572


 76%|███████▌  | 76/100 [06:33<02:03,  5.14s/it]

0.1550616171831886


 77%|███████▋  | 77/100 [06:38<02:00,  5.26s/it]

0.15400424123638207


 78%|███████▊  | 78/100 [06:43<01:54,  5.23s/it]

0.15299078873876068


 79%|███████▉  | 79/100 [06:49<01:49,  5.20s/it]

0.15202482675926554


 80%|████████  | 80/100 [06:54<01:43,  5.18s/it]

0.15109423227194282


 81%|████████  | 81/100 [06:59<01:38,  5.17s/it]

0.15020243492391375


 82%|████████▏ | 82/100 [07:04<01:32,  5.16s/it]

0.14936067029419872


 83%|████████▎ | 83/100 [07:09<01:27,  5.16s/it]

0.14855289262615973


 84%|████████▍ | 84/100 [07:14<01:22,  5.15s/it]

0.1477728651629554


 85%|████████▌ | 85/100 [07:19<01:17,  5.15s/it]

0.147029560059309


 86%|████████▌ | 86/100 [07:25<01:12,  5.16s/it]

0.14632160226917929


 87%|████████▋ | 87/100 [07:30<01:07,  5.16s/it]

0.14565020820332897


 88%|████████▊ | 88/100 [07:35<01:01,  5.16s/it]

0.14502097935312325


 89%|████████▉ | 89/100 [07:40<00:56,  5.16s/it]

0.14442587861170372


 90%|█████████ | 90/100 [07:45<00:51,  5.15s/it]

0.14385709683928224


 91%|█████████ | 91/100 [07:50<00:46,  5.15s/it]

0.14331204899483257


 92%|█████████▏| 92/100 [07:55<00:41,  5.14s/it]

0.14278537542041805


 93%|█████████▎| 93/100 [08:01<00:35,  5.14s/it]

0.14227508381009102


 94%|█████████▍| 94/100 [08:06<00:30,  5.14s/it]

0.14177946011639303


 95%|█████████▌| 95/100 [08:11<00:26,  5.25s/it]

0.14130504719085163


 96%|█████████▌| 96/100 [08:16<00:20,  5.20s/it]

0.14084444536517063


 97%|█████████▋| 97/100 [08:21<00:15,  5.18s/it]

0.14039576891809702


 98%|█████████▊| 98/100 [08:27<00:10,  5.17s/it]

0.13996162079274654


 99%|█████████▉| 99/100 [08:32<00:05,  5.16s/it]

0.13953942050122553


100%|██████████| 100/100 [08:37<00:00,  5.17s/it]

0.13912438891000217
